configurationset:
  - configuration:
      name: postgresql_config
      uri: postgres://postgres.sehtdbfjhnhdjoenlaaw:Ronnysaidthepasswordwasntstrongenough99@aws-0-eu-west-2.pooler.supabase.com:5432/postgres
